apiVersion: apps/v1
kind: Deployment
metadata:
  name: newdoc
spec:
  selector:
    matchLabels:
      run: newdoc
  replicas: 2
  template:
    metadata:
      labels:
        run: newdoc
    spec:
      containers:
        - name: newdoc
          image: arunazhagappan/nginx-image:b0a475ed20c9fba65dfda64a71e2e5e715250627
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: newdoc
  labels:
    run: newdoc
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    run: newdoc
  type: LoadBalancer
