apiVersion: apps/v1
kind: Deployment
metadata:
  name: newdoc
spec:
  selector:
    matchLabels:
      run: newdoc
  replicas: 2
  template:
    metadata:
      labels:
        run: newdoc
    spec:
      containers:
      - name: newdoc
        image: sairam
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 100Mi

---

apiVersion: v1
kind: Service
metadata:
  name: newdoc
  labels:
    run: newdoc
spec:
  ports:
  - port: 80
  selector:
    run: newdoc
  type: LoadBalancer

