name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Update deployment.yaml
        run: |
          git add deployment.yaml
          git diff --cached --quiet || git commit -m "Update image to ***/newimage:latest"

      - name: Push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://$GH_PAT@github.com/ArunAzhagappan/argo.git
          git push origin HEAD:main
