name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'  # Trigger on changes to the index.html file

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          no-cache: true  # Disable cache to ensure the image is rebuilt
          tags: arunazhagappan/newimage:latest

      - name: Print deployment.yaml before update
        run: |
          echo "Contents of deployment.yaml before update:"
          cat deployment.yaml || echo "No deployment.yaml found"

      - name: Update deployment.yaml
        run: |
          echo "Updating deployment.yaml..."
          sed -i 's|image: .*/newimage:.*|image: arunazhagappan/newimage:latest|g' deployment.yaml
          echo "Contents of deployment.yaml after update:"
          cat deployment.yaml || echo "No deployment.yaml found or no changes made"
        env:
          DOCKER_IMAGE: arunazhagappan/newimage:latest

      - name: Commit and push changes
        run: |
          echo "Committing changes..."
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add deployment.yaml
          git status
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update image to arunazhagappan/newimage:latest"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger ArgoCD sync
        run: |
          echo "Triggering ArgoCD sync..."
          curl -k -X POST https://0d66-117-242-217-241.ngrok-free.app/api/v1/applications/my-app/sync \
          -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" || { echo "Failed to trigger ArgoCD sync"; exit 1; }
        env:
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
