name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'  # Trigger on changes to the index.html file

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: arunazhagappan/newimage:latest

      - name: Trigger ArgoCD sync
        run: |
          echo "Triggering ArgoCD sync..."
          curl -k -X POST https://0d66-117-242-217-241.ngrok-free.app/api/v1/applications/my-app/sync \
          -H "Authorization: Bearer $ARGOCD_TOKEN"
        env:
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
