name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'  # Trigger on changes to the index.html file

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          no-cache: true  # Disable cache to ensure the image is rebuilt
          tags: arunazhagappan/newimage:latest

      - name: Update deployment.yaml
        run: |
          sed -i 's|image: .*/newimage:.*|image: arunazhagappan/newimage:latest|g' deployment.yaml || echo "No deployment.yaml found or no need to update"
        env:
          DOCKER_IMAGE: arunazhagappan/newimage:latest

      - name: Commit and push changes
        if: success() && env.DOCKER_IMAGE != ''
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update image to $DOCKER_IMAGE"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger ArgoCD sync
        if: success() && env.DOCKER_IMAGE != ''
        run: |
          curl -k -X POST https://argocd-server/api/v1/applications/my-app/sync \
          -H "Authorization: Bearer $ARGOCD_TOKEN"
        env:
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
