name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'  # Trigger on changes to the index.html file

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install ngrok directly (if needed)
      # - name: Download ngrok
      #   run: |
      #     curl -o ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
      #     unzip ngrok.zip
      #     chmod +x ngrok
      #     sudo mv ngrok /usr/local/bin/ngrok

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: arunazhagappan/newimage:latest  # Assuming your Docker image name is arunazhagappan/newimage:latest

      - name: Check NGINX container status
        run: |
          if docker ps -a --filter "name=newimage" --format '{{.ID}}'; then
            echo "NGINX container is already running."
          else
            echo "Starting NGINX container..."
            docker run --name newimage -d -p 8080:80 arunazhagappan/newimage:latest
          fi

      - name: Run NGINX container for tests
        run: |
          sleep 10  # Adjust sleep time based on NGINX startup time
          response=$(curl -s -I http://localhost:8080/index.html)
          echo "NGINX Test Response:"
          echo "$response"
          echo ""
          echo "NGINX Test Content:"
          curl -s http://localhost:8080/index.html
          docker logs newimage  # Output logs for debugging

      - name: Restart NGINX container if needed
        run: |
          if docker ps -a --filter "name=newimage" --format '{{.ID}}'; then
            docker restart newimage
            echo "NGINX container restarted."
          else
            echo "NGINX container does not exist or is not running. Skipping restart."
          fi

      - name: Trigger ArgoCD sync
        run: |
          echo "Triggering ArgoCD sync..."
          curl -k -X POST https://e952-117-242-217-241.ngrok-free.app/api/v1/applications/my-app/sync \
          -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" || { echo "Failed to trigger ArgoCD sync"; exit 1; }
        env:
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
