name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: arunazhagappan/nginx-image:latest,arunazhagappan/nginx-image:${{ github.sha }}

      - name: Verify Docker image update
        run: |
          docker pull arunazhagappan/nginx-image:${{ github.sha }}
          if [ "$(docker images -q arunazhagappan/nginx-image:${{ github.sha }})" == "" ]; then
            echo "Docker image was not updated"
            exit 1
          fi

      - name: Update deployment manifest
        run: |
          sed -i "s|arunazhagappan/nginx-image:.*|arunazhagappan/nginx-image:${{ github.sha }}|g" ./deployment.yaml
          git config --local user.email "ci@do-k8s-challenge.com"
          git config --local user.name "ci"
          git add ./deployment.yaml
          git commit -m "Update deployment to image version ${{ github.sha }}"
          git push origin main

      - name: Trigger ArgoCD sync
        run: |
          echo "Triggering ArgoCD sync..."
          curl -k -X POST https://e952-117-242-217-241.ngrok-free.app/api/v1/applications/my-app/sync \
          -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" || { echo "Failed to trigger ArgoCD sync"; exit 1; }
        env:
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
