name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'  # Trigger on changes to the index.html file
      - 'deployment.yaml' # Trigger on changes to the deployment.yaml file

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          no-cache: true  # Disable cache to ensure the image is rebuilt
          tags: arunazhagappan/newimage:latest

      - name: Update deployment.yaml
        run: |
          sed -i 's|image: .*/newimage:.*|image: arunazhagappan/newimage:latest|g' deployment.yaml || echo "No deployment.yaml found or no need to update"
        if: success() && needs.build.outputs.docker_build == 'true'
        env:
          DOCKER_IMAGE: arunazhagappan/newimage:latest

      - name: Debug deployment.yaml
        run: cat deployment.yaml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && success() && needs.build.outputs.docker_build == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add deployment.yaml
          git commit -m "Update image tag in deployment.yaml"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger ArgoCD sync
        run: |
          curl -k -X POST https://argocd-server/api/v1/applications/my-app/sync \
          -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}"
